### ISSUE TITLE
Flag numbers is ignored if setTimeFormat is used

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#11]
If I use the new method setTimeFormat the flag "numbers" is ignored from the XML.
No time is on the spinner. In the DropDown it works.

It is only working if I set the flags via method setFlags().

With setTimeFormat:
Morning

Without setTimeFormat:
Morning 09:00

**Comment by SimplicityApks** [comment]
OK this is a rather strange bug, will have a look into it. Thanks for reporting!

**Comment by SimplicityApks** [comment]
It seems like the naive and brutal recreation of the SpinnerAdapter in setTimeFormat() killed more than I had thought of in the beginning... Anyway it is fixed now, I'll push a new version to Maven central once the other bug is fixed. By the way, the bug occured with the more_time flag and the selection as well.

**Comment by SimplicityApks** [comment]
Fixed in release 1.1.3 (3e73e247).
