### ISSUE TITLE
Text "null" in the TimeSpinner after rotation screen

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#16]
If you select a time and afterwards you rotate your screen it shows the text "null" instead only the time.

See Screenshot:
![2015-02-15 19_46_52-5554_nexus4_5 0](https://cloud.githubusercontent.com/assets/2077218/6204436/9c706ea2-b54b-11e4-8d18-0ec156ed15fa.png)

**Comment by SimplicityApks** [comment]
You're right, funnily I noticed this issue Yesterday as well so it is already on my to do list ;). Has something to do with the secondary text not being saved appropriately, I'll find out where.

**Comment by chrisonline** [comment]
The problem I think is that the secondary text shouldn't be displayed. It is a picked time not from the smart time like afternoon. 

So there exists no secondary text.

**Comment by SimplicityApks** [comment]
Oh don't worry I already had this fixed ;). (Working on the FLAG_NUMBERS thing right now, not quite sure if it is ready...)
