### ISSUE TITLE
Hide time picker from the widget

### ISSUE THREAD

**Issue by shashi02** [SimplicityApks/ReminderDatePicker#18]
I included the widget like this:
<code><pre>com.simplicityapks.reminderdatepicker.lib.ReminderDatePicker
            android:id="@+id/dp_pick_goal_date"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:flags="mode_google|hide_time" /></code></pre>

I only want the date field and not the time picker. <b>Is there any way to achieve this?</b> Currently the <code>hide_time</code> flag shows a clock image tapping which shows the usual time options.

**Comment by SimplicityApks** [comment]
Sure, the library is designed with exactly that in mind ;). Simply replace the ReminderDatePicker in your layout file with a 'com.simplicityapks.reminderdatepicker.lib.DateSpinner' and leave everything else as it is (remove the hide_time flag as well). You can still pass flags to the DateSpinner and it should work perfectly. If you run into any issues or have questions, feel free to ask them here as this advanced approach hasn't been tested too much...

**Comment by shashi02** [comment]
Great :) Working fine. Thanks a lot for such quick response!!

**Comment by SimplicityApks** [comment]
You're welcome, glad you got it working!
