### ISSUE TITLE
Getting Year value when user selects "Pick a date..." option

### ISSUE THREAD

**Issue by shashi02** [SimplicityApks/ReminderDatePicker#21]
HI. I am getting trouble in capturing  the selected year in the DateSpinner that i have used in my code.
When ever i select a date using "Pick a date..." option and set the date using below code:

<code>
findViewById(R.id.date_spinner).setSelectedDate(Calender.getTimeInMillis());
</code>

and the above code gives me date like 4 May, 5 Apr etc.

I would like to have it this way  <b>4 May, 2015</b>. Is there some possibility for that?

**Comment by SimplicityApks** [comment]
The default behaviour is that the Spinner will show the year value only when it's not the current year, which makes sense in most use-cases. 
What you're trying to achieve is entirely possible though, you'd only need to call setDateFormat() with for instance a `new SimpleDateFormat("d MMM, yyyy")` first in your onCreate() or so. Just be aware that different languages use different date formats, so you might want to [get a default date pattern string for the current locale](http://stackoverflow.com/questions/9235934/get-preferred-date-format-string-of-android-system) to modify.

**Comment by shashi02** [comment]
It's working exactly as per my requirement. Thanks a lot :)
