### ISSUE TITLE
Adding some methods

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#27]
Can you please add some methods?

I miss "setFirstDayOfweek" and "setCloseOnSingleTapDay"!

**Comment by SimplicityApks** [comment]
Mmhh wouldn't it be easier if we just had a getter for the DatePickerDialog? That way we don't have to keep syncing with those methods as new ones are added upstream and can also easier replace the built-in DateTimePicker library

**Comment by chrisonline** [comment]
Yeah a way better. Good idea, can you add this?

**Comment by SimplicityApks** [comment]
There you go, I made it so that it returns null if a custom picker is set (so that you don't get an object that is never used and then wonder why your changes aren't visible).

**Comment by chrisonline** [comment]
Great thanks! 
I now use the Gradle compile option, so is there a way I can simple test this?
Or do I need to download the whole project and add it with "compile project"?

**Comment by SimplicityApks** [comment]
Good question, but I think there is no other way than cloning the repo and manually adding it to your build.gradle with the compile project option. That is why maven is so nice ;)

**Comment by chrisonline** [comment]
Tried it and it works, thanks!
When do you plan to make a new release?

**Comment by SimplicityApks** [comment]
Closed with 1.2.1 release
