### ISSUE TITLE
Use resources from project

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#28]
Is it possible to use the resources from the project who uses this library?
I am talking about the dropdown text elements like "select_time", "spinner_time_footer", "time_morning", ...

My app can be translated via Webinterface and I want that the dropdown can be translated too.
So it would be great to add a flag to use the resources from the project instead of the library.
If this is possible. Have never done this.

**Comment by SimplicityApks** [comment]
You should be able to override any resources by simply giving them the same name, see [here](http://stackoverflow.com/questions/4263259/replace-or-override-string-in-android-library-project). So no need for a flag, but once you've translated the strings it would be nice if you could create a pull request ;).

**Comment by chrisonline** [comment]
OK thanks, great tip!
Yes of course if my users are translated a bunch I will do that.
