### ISSUE TITLE
Changing FontFamily

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#30]
I've tried to change the font family, but it does not work.
Is it possible to change it? 
If yes, how? If no, can you add such functionality?

I need it at least at the spinner.
DropDown would be great, but not a must have.

**Comment by SimplicityApks** [comment]
What did you try to change it? I assume you'd have to override each of the @layout/twin_text_{item;footer;dropdown;...}.xml items and use the android:fontFamily attribute there. I don't know if it's worth making a separate attribute just to change the spinner font...

**Comment by chrisonline** [comment]
Thanks, I always forget the "override" thing!!
Works perfect now with the override of the twin_text elements.

So no need to add a attribute.
