### ISSUE TITLE
Parse from XML isn't working anymore

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#36]
Hi, it's me again ;-)

I have just now upgrade to Android Studio and latest Gradle version.
Now I have the problem that the DateSpinner only shows @2131689789, @213546756 and so on.
Instead of the @string/date_today strings.

I have debuged a little bit and it seems that 

`parser.getAttributeValue(i);`

inside parseItemFromXmlTag() will send back the @2131689789 instead of "string/date_today"!

```
case XML_ATTR_TEXT:
                    text = parser.getAttributeValue(i);
                    if(text != null && text.startsWith("@string/"))
                        textResource = res.getIdentifier(text, "string", packageName);
                    break;

```

Can you please check this?
Have tried it on Android 7 and 8 and on both the same result.
So it seems the problem is on the new Gradle version?!

**Comment by SimplicityApks** [comment]
There's your fix, if this works for you I'll try to do a release to maven if I have the time.

**Comment by chrisonline** [comment]
Thanks this works. Can you do please a release to maven?
Thanks again for your really quick fix.
