### ISSUE TITLE
New Theme Black

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#38]
Hi!

I just wanted to add a third theme Black to my app.
The DropDown style should of course also be black.

I have found that if I override color "footer_background" it works, but footer_background isn't an attribute so I can't change it per theme override.

Can you please change "footer_background" to an attribute so I can override it in my themes.xml per theme?

Or do you know any other way how I can change the @color/footer_background per differrent theme from my app without an attribute?

**Comment by SimplicityApks** [comment]
Does this (7596fba) work for you? I cannot add a attribute to configure it as I don't see a way to set the default background then.
Sorry it took me so long to answer, am quite busy...

**Comment by chrisonline** [comment]
Sorry for the missing answer. Seems I never got a notfication ?!!?
I have a working version with pure black already running.

So is your commit in the latest version already? If not it seems I have solved it with another way ;-)

Sorry again for my missing answer.

**Comment by SimplicityApks** [comment]
Well it's not on maven central if that's what you mean. Was waiting for your comment and then forgot about it :D So how did you solve it then?

**Comment by chrisonline** [comment]
Good question ;-)
I don't know anymore becuase it is too long since I have fixed that.
Should we close this issue?
