### ISSUE TITLE
Crash with NullPointer after setContentView

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#39]
In my Crashlytics logs I get some reports with NullPointerException.
See attaches crashlog. It happens at after `setContentView`:

![crash](https://user-images.githubusercontent.com/2077218/38827118-2e2c473a-41b2-11e8-921e-f5508f53c744.png)

**Comment by SimplicityApks** [comment]
Mmmhhhh that really looks like a strange error. Can you give me some more details on what Android version or device this is happening on?

It can somehow only be a mistake in the implementation of ArrayAdapter, as the PickerSpinner constructs a new one in initAdapter() and then calls setAdapter() with it. A subsequent call to getCount() on the ArrayAdapter should never throw a NullPointerException.

**Comment by chrisonline** [comment]
Android versions are 7, 5 and 4!
Models Huawei and Samsung.

I don't have implemented ArrayAdapter.
I use the default entries. So it should use the libraries date_items.xml so far I know.

**Comment by SimplicityApks** [comment]
Mmhh so not a single android version to blame here...

The thing is, the crash happens in ArrayAdapter.getCount(). This can only happen if its internal mObjects List null, but this is never the case if one takes a look at the source [here](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/widget/ArrayAdapter.java). At least I don't see any way this can happen with the current version of this. Might be that some different versions of the class exist in vendor modifications. That is what I meant with implementation of ArrayAdapter above. It also does not really matter how many items are in the List, mObjects should never be null in any case.

**Comment by chrisonline** [comment]
OK I understand. Really strange.
At the moment I had only about 8 users with this crash. So not a huge impact.

**Comment by chrisonline** [comment]
I think we can close this. Never had more than a few users with this crash.
